### ISSUE TITLE
Reporter screenshots

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [LironEr/cypress-mochawesome-reporter#10]
Currently I think the reporter only attach screenshots for failed tests, I think would be helpful to add the screenshots for passed tests that are taken on the fly as well.

**Comment by LironEr** [comment]
Yes, currently the reporter only attaches screenshots for failed tests.
Cypress API makes it difficult to work with screenshots, I will try to find a way to attach screenshots for passed tests as well.

**Comment by LironEr** [comment]
Released in [v1.2.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v1.2.0)
