### ISSUE TITLE
Add possibility of adding custom info to the report, something like addContext() in mochawesome-report

### ISSUE THREAD

**Issue by gustawx** [LironEr/cypress-mochawesome-reporter#109]
Would be great to be able to add a custom info to the report, something like `addContext()` in mochawesome-report.

**Comment by LironEr** [comment]
you can still use `addContext`, the context should be in the HTML report

**Comment by gustawx** [comment]
Thank you very much for feedback I will check it out

**Comment by LironEr** [comment]
I'm closing the issue, but if you need help reply here
