### ISSUE TITLE
Not able to implement imbedded screenshots 

### ISSUE THREAD

**Issue by vitaliy4us** [LironEr/cypress-mochawesome-reporter#112]
### Environment

```markdown
- OS: Windows 10
- Node: 16
- cypress-mochawesome-reporter: 3.2.3
- cypress: 10
```

### What happened?

I am trying to implement Mochawsome report to my Cypress 10 framework. I use cypress-mochawesome-reporter plugin and set it up regarding npm package instructions https://www.npmjs.com/package/cypress-mochawesome-reporter. But the problem is that the report is generated without imbedded screenshots despite of using embeddedScreenshots: true parameter in reporterOptions object. cypress/screenshots folder contains the necessary screenshots but they are missing in the report. 

P.S. I have to add an important remark. Further investigation revealed that some screenshots are embedded, but a half of them are not. On the moment of publishing this report I used only 1 test to check if the plugin work at all and got a report without screenshot. Now I have a big number of tests: 81 tests total, 26 failed, and only 15 of them have screenshots. Screenshots folder contains images for all failed tests

### Config file

```json
module.exports = defineConfig({
    video: false,
    reporter: 'cypress-mochawesome-reporter',
    reporterOptions: {
        charts: true,
        reportPageTitle: 'mochawsome',
        embeddedScreenshots: true,
        inlineAssets: true,
        saveAllAttempts: false,
  },
  e2e: {
        experimentalStudio: true,
	experimentalSessionAndOrigin: true,
	chromeWebSecurity: false,
	setupNodeEvents(on, config) {
            require('cypress-mochawesome-reporter/plugin')(on);
	    return require('./cypress/plugins/index.js')(on, config)
	},
    },
})
```

### Anything else?

<img width="589" alt="mochawspme image" src="https://user-images.githubusercontent.com/12917391/196731898-cf71d305-7db6-47d4-9663-d161bfec4750.png">

**Comment by LironEr** [comment]
Please create a repo with the problem and steps to reproduce the issue so I can have a look.

Thanks.
