### ISSUE TITLE
Can't handle screenshots outside the report folder

### ISSUE THREAD

**Issue by mikstime** [LironEr/cypress-mochawesome-reporter#114]
### Environment

```markdown
- cypress-mochawesome-reporter: 3.2.4
```

### What happened?

It is possible to move screenshot file using [After Screenshot API](https://docs.cypress.io/api/plugins/after-screenshot-api#Modify-screenshot-path) which could result in screenshot being located outside the report folder. It's clearly seen current implementation of enhanceReport function [can't handle](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/lib/enhanceReport.js#L110) such cases therefore report is not created. I believe reporter could check if provided path is absolute and copy file if so.

### Config file

```json
Not needed
```

**Comment by LironEr** [comment]
Actually, I haven't tried this, but it depends if I can get the new path [here](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/register.js#L8).

It would help if you could create an example repo with this problem so I will be able to play with and try to fix this issue
