### ISSUE TITLE
It's possible to update Size ,Color of "addContext"

### ISSUE THREAD

**Issue by matifniaz** [LironEr/cypress-mochawesome-reporter#115]
For Example :
`Entered Username: <b><font color=SpringGreen>admin_core12121121212</b> </font>on Login Page`

**Result on Report:** 
Entered Username: **admin_core12121121212**on Login Page

Currently, HTML not rendering, Snapshot for reference:
![image](https://user-images.githubusercontent.com/40147842/202644650-e35be1e3-78af-44f4-ad62-e467f0e574b3.png)

**Comment by LironEr** [comment]
Currently, this is not possible.

Under the hood, this reporter uses [mochawesome](https://github.com/adamgruber/mochawesome), which is responsible for the `addContext` function & the HTML report.

You can try to open a feature request there (:
