### ISSUE TITLE
Random code is shown in cypress report and screenshots are not embedded

### ISSUE THREAD

**Issue by KiranmaiLL** [LironEr/cypress-mochawesome-reporter#130]
### Environment

```markdown
- OS: MAC
- Node: latest
- cypress-mochawesome-reporter: latest (3.2.0)
- cypress: 10 , 11, 12 (tried with all)
```

### What happened?

Screenshots stopped getting attached in the reports when I changed the cypress-cucumber-processor to @badeball/cypress-cucumber-preprocessor and random code is shown under every test case under report 

### Config file

```json
const { defineConfig } = require('cypress')
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");

module.exports = defineConfig({
  chromeWebSecurity: false,
  video: false,
  defaultCommandTimeout: 12000,
  execTimeout: 60000,
  pageLoadTimeout: 60000,
  requestTimeout: 15000,
  responseTimeout: 15000,
  projectId: 'ov3y5h',
  retries: 1,
  screenshotOnRunFailure: true,
  reporter: 'cypress-mochawesome-reporter',
  
  reporterOptions: {
  
      charts: true,
      reportPageTitle: 'My Test Suite',
      embeddedScreenshots: true,
      inlineAssets: true,
     
  },
  e2e: {

    setupNodeEvents(on, config) {
  
      preprocessor.addCucumberPreprocessorPlugin(on, config);
      require('cypress-mochawesome-reporter/plugin')(on);
    
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin.default(config)],
        })    
      );
    
      return config;
    },
    baseUrl: 'https://application.com',
    excludeSpecPattern: [
      '**/cucumber-tests/**/*[!*.feature]',
      '**/common/**',
      '**/assets/**',
      '**/utils/**',
      '*.md',
    ],
    specPattern: 'cypress/e2e/**/*.feature',
    supportFile: false,
  }

})
```

### Anything else?

<img width="1511" alt="reportCypress" src="https://user-images.githubusercontent.com/91728173/216174572-81a0eabc-ed4f-4506-afd0-025e6b0b629f.png">

**Comment by LironEr** [comment]
I'm not familiar with `cypress-cucumber-preprocessor`, but if you provide a repo with the issue I can try to have a look

**Comment by KiranmaiLL** [comment]
Unfortunately, I wouldn't be able to provide the repo details!

**Comment by KiranmaiLL** [comment]
Hey! Thanks for getting back. Here's the repo https://github.com/KiranmaiLL/DemoProject

**Comment by gmarinov** [comment]
having the same issue, using the webpack-flavour version of the same preprocessor. I _think_ it is something to do with source maps, but the few threads I could find all seem to be waiting on something else.

to be clear, where the report lists code, I expect to see the Cucumber source code, e.g.

```
  When I visit the page
  Then I should see the title
  And I should see a link
```

actual: as on the screenshot above.

**Comment by Radik24** [comment]
Hi, @samwatts98 maybe it can help you... I forgot to add `import 'cypress-mochawesome-reporter/register';` to `cypress/support/e2e.ts` and suddenly it started working.

**Comment by samwatts98** [comment]
@Radik24 Hello mate,
Appreciate the time to respond :) However I'm currently doing that, and still getting the same result:

cypress/support/e2e.ts:
![image](https://user-images.githubusercontent.com/36446362/228565399-1ab06ddc-057c-4bdf-a9ff-5e3ddb230cd0.png)

As well as setting up the hooks as mentioned in step 2 of the set up here: https://www.npmjs.com/package/cypress-mochawesome-reporter

Yet still the reports that are produced include the Cucumber internals rather than details of the Cucumber scenario:
![image](https://user-images.githubusercontent.com/36446362/228565998-5f93006a-8b08-4b48-be0f-7ff0682dae4d.png)

**Comment by samwatts98** [comment]
@Radik24 Are you able to get these reports with the @badeball/cypress-cucumber-preprocessor then?

**Comment by XaviF-C** [comment]
I'm currently having the same issue, any updates yet?
It seems like an error from the @badeball/cypress-cucumber-preprocessor

**Comment by Sravs1308** [comment]
I'm currently having the same issue, any updates yet?

**Comment by Dale-777** [comment]
Just adding another comment to this, experiencing exactly the same issue

**Comment by LironEr** [comment]
Hey everyone, sorry for the very late response.

Thank you @KiranmaiLL for providing the demo repo, I tried to find a solution for this issue, but the problem is with the `file:preprocessor` hook, as it changes the code that cypress use then pass the code to the reporter.

If in some way we can link between the test that cypress is running and the code before the transformation we can probably override the code that you see in the final report.

Other then that, I cant think of a solution to this issue, feel free to explore more and if someone comes up with something I will be more then happy to help make it work.

**Comment by NareshNama** [comment]
Any update on this issue ?

**Comment by ajling** [comment]
Hi Everyone,
I've just updated two of my Cypress test repositories with 'cypress-mocha-awesome' version 3.5.1 and I'm no longer seeing any of the extra js code appearing in the reports.
My versions are:
Cypress v12.14.0 and v12.17.1, 
Mochawesome v7.1.3

I also updated my reporter options to the below (not sure if it makes much of a difference though):
reporterOptions: {
    charts: true,
    reportTitle: "UI Test Report",
    reportPageTitle: "UI Test Report",
    reportDir: "cypress/reports",
    reportFilename: "myReport",
    embeddedScreenshots: true,
    inlineAssets: true,
    saveAllAttempts: false,
    charts: true,
    code: false,
    showPassed: true,
    showFailed: true,
    showPending: false,
    showSkipped: false,
  },

Hopefully it works for you guys too

**Comment by ClareChallis** [comment]
I am having this issue still, is there any update?

**Comment by mistic100** [comment]
@LironEr can you please reopen this issue ? I have made some progress and I think a solution is possible.

Currently I am able to modify `@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js` and pass the Cucumber source to Mochawesome via `addTestContext`.
 
```js
cy.addTestContext({
    title: 'Cucumber source',
    value: pickleSteps
        .map(step => step.text)
        .join('\n'),
});
```

here https://github.com/badeball/cypress-cucumber-preprocessor/blob/7cdb1feb03239f11ec14907b819be78c0f32d19d/lib/browser-runtime.ts#L447

This way the cucumber source is available inside the report.

There some work left to do :
- apply this modification without having to modify the node_modules (perhaps ask cypress-cucumber-preprocessor to add some kind of hook)
- conditionally hide the actual source code (I have a mix of `.feature` and `.cy.ts` files so I cannot just set `code: false`
- handle more complex Cucumber code like Data Table and Outlines
