### ISSUE TITLE
Marge Json output with html report

### ISSUE THREAD

**Issue by soumyajit2pal** [LironEr/cypress-mochawesome-reporter#134]
Hi,
Rather than deleting all JSON files after creating the HTML report, can we get the marge JSON file along with the HTML report? it will help us with some other validation.

**Comment by joakim-sch** [comment]
I mean you could do #135 but it seems a bit overkill to have an option just for that...

Will leave it up to @LironEr to if it makes any sense...

**Comment by soumyajit2pal** [comment]
Hi @joakim-sch,
Thanks for the enhancement PR. JSON files are needed for someone doing test case pass/fail on the ALM tool using JSON and it's easy to use.

**Comment by LironEr** [comment]
Hey @soumyajit2pal 
You can already do that by adding `saveJson: true` to `reporterOptions`, it will keep the merged JSON file next to the HTML file.

```js
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    saveJson: true
  },
  e2e: {
    setupNodeEvents(on, config) {
      require('cypress-mochawesome-reporter/plugin')(on);
    },
  },
});
```

Let me know if this is what you needed, if not I can look at the PR (thanks @joakim-sch)

**Comment by joakim-sch** [comment]
@LironEr Ah, the option already exists in the report generator. Nice.
@soumyajit2pal documented here: [adamgruber/mochawesome-report-generator/README.md](https://github.com/adamgruber/mochawesome-report-generator/blob/5a2f079f265ccf37ec61c71bfafec37beb8ac704/README.md?plain=1#L95)

**Comment by bdimitrovski** [comment]
How does this work for `cypress-multi-reporters`? I have a config like this: 

```json
{
    "reporterEnabled": "cypress-mochawesome-reporter, mocha-junit-reporter",
    "reporterOptions": {
        "charts": true,
        "reportPageTitle": "Cypress E2E Tests",
        "embeddedScreenshots": true,
        "inlineAssets": true,
        "saveJson": true
    },
    "mochaJunitReporterReporterOptions": {
        "mochaFile": "../tests/cypress/reports/junit/[hash].xml"
    }
}
```

however, I cannot seem to get `index.json` as test results after the test run, no matter how I configure. 

Is this possible to achieve at all?
