### ISSUE TITLE
Report json it is not showing the steps

### ISSUE THREAD

**Issue by fgaliazzo** [LironEr/cypress-mochawesome-reporter#148]
I noticed that the cucumber step and its status are not referenced in the json. it's normal?

          "tests": [
            {
              "title": "Simulação",
              "fullTitle": "Pagamento",
              "timedOut": null,
              "duration": 346184,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": "",
              "code": "",
              "err": {
                "message": "AssertionError: Timed out retrying after 300000ms: expected true to be false",
                "estack": "AssertionError: Timed out retrying after 300000ms: expected true to be false\n    at Context.eval (cypress/support//globalCommands.js:40:49)",
                "diff": null
              },
              "uuid": "12e0ca-57e9-4abc-ac9b-8480baa7f696",
              "parentUUID": "be5be9-88f0-480c-9dc4-3fa026f11317",
              "isHook": false,
              "skipped": false
            },

**Comment by LironEr** [comment]
What do you mean by steps? maybe the code of the test?
Not sure I understand, anyway it will be best if you can create a repo with the problem and steps to reproduce the issue so I can have a look.

Thanks.
