### ISSUE TITLE
Compatibility with https://github.com/currents-dev/cypress-cloud

### ISSUE THREAD

**Issue by firmanserdana** [LironEr/cypress-mochawesome-reporter#151]
**Is your feature request related to a problem? Please describe.**
cypress runner alt, cypress-cloud will always reset the runner for each spec file and hereby deleting report files, previously using cy2, this was not the case

**Describe the solution you'd like**
Allow innate option to overcome this

**Describe alternatives you've considered**
I just manually merge and generate report without using this package

**Additional context**

**Comment by LironEr** [comment]
To fully understand, do you want this reporter to export a function or a CLI command that merges multiple JSONs and creates a final HTML report? 

It will be very helpful for you to provide a repo with your current configurations and steps to reproduce the issue so I can look.

Thanks.

**Comment by LironEr** [comment]
Check out cypress-parallel setup guide, its also running each spec file separately
https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/examples/cypress-parallel

Should help also in this case, if not please create an example repo so I can try to make it work.
