### ISSUE TITLE
Video included with wrong path with changed specPattern

### ISSUE THREAD

**Issue by pathob** [LironEr/cypress-mochawesome-reporter#160]
### Environment

```markdown
- OS: Docker image cypress/included:13.2.0
- Node: 20.6.1
- cypress-mochawesome-reporter: 3.6.0
- cypress: 13.2.0
```

### What happened?

When I change the `specPattern` in the Cypress config to a path outside the `./cypress/` directory, the videos are not included with the right path in the generated report.

E.g. if I set `specPattern: 'releases/**/tests/*-e2e.cy.js` and have the following tests:

- `releases/release1/tests/test1-e2e.cy.js`
- `releases/release2/tests/test2-e2e.cy.js`

Then the report tries to include the generated videos using the following paths:

- `videos/releases/release1/tests/test1-e2e.cy.js.mp4`
- `videos/releases/release2/tests/test2-e2e.cy.js.mp4`

Even though the videos are actually located at:

- `videos/release1/tests/test1-e2e.cy.js.mp4`
- `videos/release2/tests/test2-e2e.cy.js.mp4`

All under `cypress/reports/html` of couse.

### Config file

```javascript
module.exports = defineConfig({
  e2e: {
    specPattern: 'releases/**/tests/*-e2e.cy.js',

    // enable extended mochawesome reports
    setupNodeEvents(on, config) {
      require('cypress-mochawesome-reporter/plugin')(on);
    },
  },

  // record video
  video: true,

  // ...
}
```

**Comment by joakim-sch** [comment]
Hi @pathob 
Thanks for your feedback.

Could you set `debug = true` in the reporterOptions and share the debug log file?
In particular, I am looking for the baseFolder logged parameter.
Thanks!
