### ISSUE TITLE
npm i install giving error

### ISSUE THREAD

**Issue by MehranShafqat** [LironEr/cypress-mochawesome-reporter#18]
When I try to install this package its giving 

"npm ERR! code Unknown system error -83npm ERR! code Unknown system error -83"

My node version is 12.18.1

**Comment by LironEr** [comment]
Please provide more information

Run and paste the output here 
```
npx envinfo --system --binaries --markdown
```

```
npm i --save-dev cypress-mochawesome-reporter --verbose
```

Thanks

**Comment by MehranShafqat** [comment]
@LironEr 

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   '--save-dev',
npm verb cli   'cypress-mochawesome-reporter',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.5
npm info using node@v12.18.2
npm verb npm-session 5f73c470a78b1bde
npm http fetch GET 200 https://registry.npmjs.org/cypress-mochawesome-reporter 1686ms
npm timing stage:loadCurrentTree Completed in 2524ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 320ms
npm http fetch GET 304 https://registry.npmjs.org/yargs 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 241ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 2ms
npm timing stage:runTopLevelLifecycles Completed in 4205ms
npm verb stack Error: Unknown system error -83: Unknown system error -83, open '/Users/apple/.npm/_cacache/index-v5/6a/a7/1cbd001cd62203bc47d9086e371da3823c4fe7cb824efdfcccee13ad1ce3'
npm verb cwd /Users/apple/Desktop/appscience/ATS
npm verb Darwin 20.3.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "cypress-mochawesome-reporter" "--verbose"
npm verb node v12.18.2
npm verb npm  v6.14.5
npm ERR! code Unknown system error -83
npm ERR! syscall open
npm ERR! path /Users/apple/.npm/_cacache/index-v5/6a/a7/1cbd001cd62203bc47d9086e371da3823c4fe7cb824efdfcccee13ad1ce3
npm ERR! errno -83
npm ERR! Unknown system error -83: Unknown system error -83, open '/Users/apple/.npm/_cacache/index-v5/6a/a7/1cbd001cd62203bc47d9086e371da3823c4fe7cb824efdfcccee13ad1ce3'
npm verb exit [ -83, true ]
npm timing npm Completed in 4949ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2021-02-22T13_32_49_620Z-debug.log

**Comment by LironEr** [comment]
I don't think it's really a problem with this plugin, but with npm.
```
npm verb stack Error: Unknown system error -83: Unknown system error -83, open '/Users/apple/.npm/_cacache/index-v5/6a/a7/1cbd001cd62203bc47d9086e371da3823c4fe7cb824efdfcccee13ad1ce3'
```

try to delete npm cache with:
```
npm cache clean --force
```

then try to install again and paste the output:
```
npm i --save-dev cypress-mochawesome-reporter --verbose
```

if it still doesn't work try to install the latest node v12 version and try again
I'm using node v12.20.2 with npm v6.14.11

**Comment by MehranShafqat** [comment]
@LironEr  yes issue was with npm. Thanks for the quick response
