### ISSUE TITLE
Provide JSON reports 

### ISSUE THREAD

**Issue by vaclavGabriel** [LironEr/cypress-mochawesome-reporter#187]
**Is your feature request related to a problem? Please describe.**
Hello team, I'm running multiple tests in parallel and require JSON files to generate an HTML report from all instances in a subsequent job. 

Is it possible to create a **merged JSON report** in addition to the HTML report? 

**Describe the solution you'd like**
When generating the HTML report, [all JSON files from each test are merged](https://github.com/LironEr/cypress-mochawesome-reporter/blob/e6067aa249ad547734640fcf85fffbef729f6482/lib/generateReport.js#L12). 
My suggestion is to add `jsonReport` reporter option. When this option is enabled, the merged JSON report will be saved along with the HTML report.

**Describe alternatives you've considered**
I have explored the [mochawesome package](https://github.com/adamgruber/mochawesome), but cypress-mochawesome-reporter offers more options and is easier to use.

**Additional context**

**Comment by LironEr** [comment]
If I understand correctly, you can already do that, see https://github.com/LironEr/cypress-mochawesome-reporter/issues/134#issuecomment-1473621103

**Comment by vaclavGabriel** [comment]
You're correct, thanks for pointing that out! 🙂
