### ISSUE TITLE
`cypress-multi-reporter` with `configFile` option

### ISSUE THREAD

**Issue by FlaTutu** [LironEr/cypress-mochawesome-reporter#19]
**Describe the bug**
When generate report, the config file `cypress.json` is parsed to take account of reporter options, looking for special keys `reporterEnabled` and `cypressMochawesomeReporterReporterOptions` to be compliant with `cypress-multi-reporter` reporter, but completely ignore configuration if the real `cypress-multi-reporter` reporter config file is relocated with `configFile` option.

**Expected behavior**
When generate report, this reporter is fully compatible with `cypress-multi-reporter` reporter options and take account of relocated config file specified with `configFile` option key.

**Environment**
`cypress-mochawesome-reporter` version: `1.3.0`
`cypress` version: `6.7.1`

Please run this command inside your project and paste its contents here (it automatically copies to your clipboard)
`npx envinfo --system --binaries --markdown | npx clipboard-cli`

**Additional context**
## System:
 - OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 5.87 GB / 12.38 GB
 - Container: Yes
 - Shell: 5.0.3 - /bin/bash
## Binaries:
 - Node: 14.15.2
 - npm: 6.14.9

(My environment is in WSL2 and Node Docker image)

**Comment by LironEr** [comment]
Thanks for reporting this bug. 

In a few days I will release v2 for this reporter, after that I will try to fix that behavior

**Comment by LironEr** [comment]
Try `2.0.1-beta.0`

```
npm i cypress-mochawesome-reporter@2.0.1-beta.0
```

Please let me know if it solves the bug

**Comment by FlaTutu** [comment]
Ok, I got an Error on v2.0.0, but the v2.0.1-beta.0 fix it and the config specified in config file is taken into account
