### ISSUE TITLE
Screenshots are not attached to html report

### ISSUE THREAD

**Issue by Uriyay2** [LironEr/cypress-mochawesome-reporter#192]
### Environment

```markdown
- OS: MAC
- Node: 16.15.1
- cypress-mochawesome-reporter: 3.8.2
- cypress: 12.13.0
```

### What happened?

In the generated html report screendshots and videos are not dispayed, though the assets directory indeed created. the videos and screenshots folders are created as well.
what am i missing?
<img width="329" alt="Screenshot 2024-05-01 at 11 21 21" src="https://github.com/LironEr/cypress-mochawesome-reporter/assets/149956922/c76fb788-2097-4f04-83d1-8ff1ddd5dca5">
![Uploading Screenshot 2024-05-01 at 11.23.02.png…]()

### Config file

```json
module.exports = defineConfig({
  reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    reportsDir: 'cypress/reports',
    charts: true,
    reportPageTitle: E2E Test Report',
    reportTitle: 'E2E Test Report',
    embeddedScreenshots: true,
    saveAllAttempts: true,
    ignoreVideos: true,
    videoOnFailOnly: true
  },
  screenshotOnRunFailure: true,
  video: true,
  e2e: {
    setupNodeEvents(on, config) {
      require('cypress-mochawesome-reporter/plugin')(on);
}
```

**Comment by Uriyay2** [comment]
<img width="1424" alt="Screenshot 2024-05-01 at 11 23 02" src="https://github.com/LironEr/cypress-mochawesome-reporter/assets/149956922/d5df9dce-a10d-4f66-bbdf-956904f33a6d">

**Comment by guy-pimloc** [comment]
https://github.com/LironEr/cypress-mochawesome-reporter/issues/166#issuecomment-1936732444

Have you tried this,  I was having the same issue and this solved it

**Comment by Uriyay2** [comment]
@guy-pimloc Thanks!
I had to changed to configuration to my supoort e2e.js file and it works fine.
