### ISSUE TITLE
code in generated report is javascript, instead of original typescript

### ISSUE THREAD

**Issue by stealthrabbi** [LironEr/cypress-mochawesome-reporter#198]
### Environment

```markdown
- OS: Win 10
- Node: 18
- cypress-mochawesome-reporter:  3.8.2
- cypress: 13.11.0
```

### What happened?

When I generated the report, I see the included source code for the test is the javascript code, and not the original typescript

### Config file

```json
(using default provided on readme)
```

**Comment by LironEr** [comment]
Please create a repo with the problem and steps to reproduce the issue so I can have a look.

Thanks.
