### ISSUE TITLE
Access Cypress test retries in the jUnit report

### ISSUE THREAD

**Issue by viktorgagaleski** [LironEr/cypress-mochawesome-reporter#199]
**Is your feature request related to a problem? Please describe.**
Currently I don't see trace of the retries in the jUnit report. 

**Describe the solution you'd like**
We would like to use the retries as they point to flaky tests. It probably needs to be a property that has information that a test has been retried.

**Describe alternatives you've considered**

**Additional context**
Not sure if I am missing some configuration, or this is not possible at the moment.

**Comment by BryonSullivan** [comment]
I also ran into this and am unable to figure out how to get that data from retries into my report. I thought that I was overlooking something, but it appears not.

**Comment by LironEr** [comment]
Not sure I fully understand the issue as this is not a junit reporter. 
If you still think this reporter should do that, please create a repo with the problem and steps to reproduce the issue so I can have a look.

Thanks.
