### ISSUE TITLE
Reporter output folder option

### ISSUE THREAD

**Issue by FlaTutu** [LironEr/cypress-mochawesome-reporter#20]
**Is your feature request related to a problem? Please describe.**
The HTML target report directory is hard-fixed to `cypress/reports/html` but I want to specify a custom one.

**Describe the solution you'd like**
Specify the directory where HTML report file is written by an option in reporter config (`outputFolder` for example).

**Describe alternatives you've considered**
I don't have alternatives as long as I know.

**Environment**
cypress-mochawesome-reporter version: 1.3.0
cypress version: 6.7.1

**Additional context**
## System:
 - OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 5.87 GB / 12.38 GB
 - Container: Yes
 - Shell: 5.0.3 - /bin/bash
## Binaries:
 - Node: 14.15.2
 - npm: 6.14.9

(My environment is in WSL2 and Node Docker image)

**Comment by LironEr** [comment]
Hey,

This option is already available with -o/--output flag ([cli flags](https://github.com/LironEr/cypress-mochawesome-reporter#cli-generate-mochawesome-report-flags))

example:
```
generate-mochawesome-report --output custom/output/path
```

if you want to put it in the `scripts` section in `package.json`:
```
"cypress:report": "generate-mochawesome-report --output custom/output/path"
```

**Comment by FlaTutu** [comment]
Hello @LironEr 
Thanks for your response, I saw that it is possible in cli flags, but not in config files 🙂

I prefer centralize different settings that change the behavior of the plugin in one place, and avoid to have some options in config file and anothers in npm script with cli flags. To go deeper, if I just put cli flag in npm script, I can't be sure the option will always be taken into account. Indeed, some users can use `npx` directly to launch script, or I can have some docker containers in ci pipelines which have only `node` binary and not `npm` and it will directly call the `node_modules\.bin\generate_mochawesome_report`, in this case I have to synchronise cli flags of npm script and this one. With config files, I don't have to think to that.
Last point, I already have in config file the settings of others reporters, again, centralized settings of all my reporters in one config file seems better that use cli flags.

**Comment by LironEr** [comment]
In a few days I will release v2 for this reporter, the reporter won't need the CLI part at all.
It will create the HTML report at the end of a test run with the config provided in cypress.json

I will update here as soon as I have a beta version ready

**Comment by FlaTutu** [comment]
That's sounds great, I will love this v2 for sure 🙂

**Comment by LironEr** [comment]
[v2.0.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.0.0) has been released 🎉🎉

In order to change the output folder add `reportDir` to `reporterOptions` in your `cypress.json` file
```
{
  "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "reportDir": "cypress/custom-report-path"
  }
}
```

**Comment by FlaTutu** [comment]
Ok, v2 fix this issue 🎉
Thanks for your reactivity 👍🏽
