### ISSUE TITLE
Error: unexpected token {

### ISSUE THREAD

**Issue by vadal** [LironEr/cypress-mochawesome-reporter#3]
Hello! 
First of all, thank you for the plugin!

I have the following issue when I run the command to the server.
Can you please help me?

<img width="863" alt="Screenshot 2020-06-29 at 4 39 03 PM" src="https://user-images.githubusercontent.com/4260120/86012943-4443b400-ba27-11ea-9e3b-79ae34873f45.png">

**Comment by vadal** [comment]
@LironEr any idea? :)

**Comment by LironEr** [comment]
what node version do u use?
Looks like the minimum version should be node 10, I will add it to the readme file
