### ISSUE TITLE
Option to convert screenshot to base64

### ISSUE THREAD

**Issue by leonardosimoura** [LironEr/cypress-mochawesome-reporter#30]
**Is your feature request related to a problem? Please describe.**
Option to convert screenshot  to base64, combined with inlineAssets (reportOption) will be possible to generate a single html file and use in some platforms ( like Azure Dev Ops) with tools/extensions that support publish html reports (example: https://marketplace.visualstudio.com/items?itemName=LakshayKaushik.PublishHTMLReports)
**Describe the solution you'd like**
A report option (For example "ScreenshootToBase64".
Before call reportGenerator.create made this conversion in json files
**Additional context**
Let me know if this is a good feature, i like to contribute with a PR with this.

**Comment by LironEr** [comment]
Sounds like a good feature, I will go over the PR later this week.

Thanks for contributing! 😊

**Comment by LironEr** [comment]
Released in [v2.1.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.1.0)

Thanks @leonardosimoura
