### ISSUE TITLE
Include spec's filename in its corresponding result page

### ISSUE THREAD

**Issue by quad5** [LironEr/cypress-mochawesome-reporter#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I am using v1.3.0. Sorry if it is already implemented in newer version. What I am asking is if spec name can be included in its corresponding result page. At the moment, I see describe's string value as title. 

**Describe alternatives you've considered**

**Additional context**

**Comment by quad5** [comment]
Please let me know if this is something I should file against mochawesome. Thanks.

First two pictures are from my test output:
   - Notice the 2nd image has spec path. I do *not* have `it` within `describe` in that spec file. 
   - Notice the 1st image does *not* have spec path. I do have `it` within `describe` in that spec file.

The 3rd image is from mochawesome github readme. Notice it has both describe title and spec path.

<img width="1156" alt="Untitled22" src="https://user-images.githubusercontent.com/2043287/121600537-76141780-c9f9-11eb-913b-1c213686ba35.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2043287/121600638-9ba12100-c9f9-11eb-9a31-098d40577b36.png">

EXTRACTED FROM [mochawesome](https://github.com/adamgruber/mochawesome)
<img width="1680" alt="Untitled23" src="https://user-images.githubusercontent.com/2043287/121601282-97c1ce80-c9fa-11eb-92c7-994f0982b712.png">

**Comment by LironEr** [comment]
After digging in `mochawesome` and `mochawesome-report-generator` code it looks like when running `mochawesome` with cypress the filename exists in another place than what `mochawesome-report-generator` expects.

I will release a version later today that mitigates this problem.

**Comment by LironEr** [comment]
Released in [v2.1.1](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.1.1)

Thanks @quad5
