### ISSUE TITLE
Save the json files

### ISSUE THREAD

**Issue by pavel-R5** [LironEr/cypress-mochawesome-reporter#33]
**The issue:**
Currently I'm trying to implement Cypress and Testrail integration. In order to do that, I am planning to use [this](https://github.com/sumcumo/cypress-testrail-reporter) reporter. But as long as cypress-mochawesome-reporter delete the initial json files with the results, I'm unable to continue.

**Question/Feature I'd like to see:**
Any way how I can save both the html report and initial json files?

Thanks in advance!

**Comment by pavel-R5** [comment]
If that is an option and maybe it is easier to implement: instead of saving all initial json files, there is more sence to save one final json which has all initial json files merged.

**Comment by LironEr** [comment]
All [mochawesome-report-generator flags](https://github.com/adamgruber/mochawesome-report-generator#cli-flags) can be used with this reporter

`cypress.json`
```json
{
  "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "saveJson": true
  }
}
```

this will save a JSON file with the final report

**Comment by pavel-R5** [comment]
Hey @LironEr , thank you for your answer.
It is weird but in my case, I have it set in config. I'm using a [multi reporter](https://github.com/you54f/cypress-multi-reporters) and two reporters with their own options in the `reporter-config.json` file.

![image](https://user-images.githubusercontent.com/73487929/121590757-602a4500-ca41-11eb-9b19-afb34bd25545.png)

And weird enough, I can see during the run all json files appear, but after html generation - it seems like it overwrite the `reports` folder completely and no json files saved after that.

Maybe you can give me a clue, what am I missing?

P.S.: I even tried to set it both in `cypress.json` and in `reporter-config.json` but it didn't help...

**Comment by LironEr** [comment]
Try like this:
```json
{
  "reporterEnabled": "cypress-mochawesome-reporter, mocha-junit-reporter",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "cypress/results/xml/test-result-[hash].xml"
  },
  "cypressMochawesomeReporterReporterOptions": {
    "saveJson": true
  }
}
```

**Comment by pavel-R5** [comment]
@LironEr Thank you, it works!
Great reporter, keep up what you are doing! :)
