### ISSUE TITLE
The final HTML report is note getting generated

### ISSUE THREAD

**Issue by ganeshsirsi** [LironEr/cypress-mochawesome-reporter#35]
I have configured this plugin it worked fine the first time when I run the report
Later due to my framework configuration I have put the below code in `plugin/index.js`
```
module.exports = (on, config) => {
  on('after:run', (results) => {
        const exec = require('child_process').execSync
      try{
       exec('npx jrm cypress/mergedreport.xml ./cypress/reports/junit/*.xml');
      }
      catch(error){
        console.log(error);
      }
  });
}
```

The above code is nothing to do with HTML reporters though, but final HTML is not getting generated because of the above code.
Kindly fix the bug. I was thinking to write a detailed article about multiple reporters using this plugin but this bug is stopping me.

**So the issue here is if I override before:run and after:run to write some code this doesn't work**

**Comment by LironEr** [comment]
released in [v2.2.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.2.0)

**Comment by ganeshsirsi** [comment]
@LironEr  connect with me on LinkedIn Once I finish the article will share it with you. https://www.linkedin.com/in/ganeshsirsi/

**Comment by ganeshsirsi** [comment]
@LironEr Here is the first article https://dev.to/ganeshsirsi/cypress-how-to-configure-html-results-with-screenshot-step-by-step-guide-55n7  Feel free to share it will be helpful for beginners.
More articles might come using the same plugin.
