### ISSUE TITLE
Add quiet flag

### ISSUE THREAD

**Issue by endercrest** [LironEr/cypress-mochawesome-reporter#37]
**Is your feature request related to a problem? Please describe.**
Upgraded from v1 of this and now getting additional logging which isn't wanted

**Describe the solution you'd like**
Be able to pass `queit: true` into `reporterOptions` to stop all logging

**Describe alternatives you've considered**

**Additional context**

**Comment by LironEr** [comment]
released in [v2.2.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.2.0)
