### ISSUE TITLE
Unable to generate report using v2.1.1

### ISSUE THREAD

**Issue by quad5** [LironEr/cypress-mochawesome-reporter#38]
**Describe the bug**

Using version 2.1.1, I get this error when running `npm run cypress:report`. Works fine for 1.3.0.

Extract from "/.npm/_logs/2021-06-15T22_29_08_472Z-debug.log"
> 10 silly lifecycle automation-testing@1.0.0 cypress:report: Args: [ '-c', 'generate-mochawesome-report' ]
11 info lifecycle automation-testing@1.0.0 cypress:report: Failed to exec cypress:report script
12 verbose stack Error: automation-testing@1.0.0 cypress:report: `generate-mochawesome-report`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

> 15 verbose Darwin 20.1.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "cypress:report"
17 verbose node v12.18.4
18 verbose npm  v6.14.10
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error automation-testing@1.0.0 cypress:report: `generate-mochawesome-report`
23 error spawn ENOENT
24 error Failed at the automation-testing@1.0.0 cypress:report script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Expected behavior**

**Environment**
`cypress-mochawesome-reporter` version: `<VERSION>`
`cypress` version: `<VERSION>`

Please run this command inside your project and paste its contents here (it automatically copies to your clipboard)
`npx envinfo --system --binaries --markdown | npx clipboard-cli`

**Additional context**

**Comment by LironEr** [comment]
See the [migration guide](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/migration.md#migrating-from-v1-to-v2) from v1 to v2

**Comment by quad5** [comment]
Works after I update as instructed in migration guide.
