### ISSUE TITLE
Video Embed Possible?

### ISSUE THREAD

**Issue by parky128** [LironEr/cypress-mochawesome-reporter#43]
Hi, is it possible to get video's embedded as links or something similar into the generated HTML report?

Thanks

**Comment by LironEr** [comment]
Currently no, because we cant add context per suite/spec file.
Related issues: https://github.com/adamgruber/mochawesome-report-generator/issues/124 https://github.com/adamgruber/mochawesome-report-generator/issues/150

**Comment by SriSivaBatchu** [comment]
Hi @LironEr 

Instead of waiting for the context for suite. I thought of adding a test entry (provided below) in tests array, after cypress execution just like enhanceReport function updating the context, here I'm adding a test entry. 
When using file name I'm able to see the video in the HTML file, but I had to share the video along with the html report.  
Could you please suggest a way to add the video in the embedded format. I tried some ways they didn't worked.
`      suitesMap.forEach((suiteEntry) => {
        suiteEntry.tests.push({
          title: "Execution Video",
          fullTitle: "Test Execution Video",
          timedOut: null,
          duration: 1,
          state: "passed",
          speed: "fast",
          pass: true,
          fail: false,
          pending: false,
          context: JSON.stringify({
            title: "Execution video",
            value: videoDetails.embeddings.data
          }),
          code: "",
          err: {},
          uuid: "f4c9b97d-f7cc-45e3-a383-852df0eec2d2",
          parentUUID: "b43632da-b240-4fe7-a130-c29065bd5f87",
          isHook: false,
          skipped: false
        })
      })`

**Comment by mudit94** [comment]
hi @LironEr , any progress in this?

**Comment by LironEr** [comment]
> Currently no, because we cant add context per suite/spec file. Related issues: [adamgruber/mochawesome-report-generator#124](https://github.com/adamgruber/mochawesome-report-generator/issues/124) [adamgruber/mochawesome-report-generator#150](https://github.com/adamgruber/mochawesome-report-generator/issues/150)

@mudit94 unfortunately no

**Comment by joakim-sch** [comment]
So it seems that Bahmutov embeds the video file for the whole suite to the test(s) that fail.
:thumbsdown: Same videofile might be embedded on several failed tests
:thumbsdown: Videofile for failed tests will contain alot more tests than the one you are looking for
:thumbsup: Embedded videofile 👏🏼

**Comment by kris-luminar** [comment]
This feels like were making some progress at last!

**Comment by joakim-sch** [comment]
Gave it a try with #137 , give it a look and let me know what you think 😸

**Comment by LironEr** [comment]
@joakim-sch Great work!

Released in [v3.4.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v3.4.0)

**Comment by Amy-B-Tradition** [comment]
This seems to not result in a playable file on Windows if your specs are organized in directories. For example
e2e/
  feature1/
     test.a.thing.cy.ts
     test.something.else.cy.ts

results in 
src="videos\cypress\e2e\feature1/test.a.thing.cy.ts.mp4"
