### ISSUE TITLE
 failed screenshots are not attached to report at embedded child "describe"  scenario

### ISSUE THREAD

**Issue by elsakhiy** [LironEr/cypress-mochawesome-reporter#45]
Hi, the report is not able attach failed screenshots when the spec file contains embedded "describe ". please see below example   

describe("Cypress Testing", () => {
    describe('Test scenario', function () {
        it('positive testing', function () {
            cy.log("test ");
        });
    });

**Comment by LironEr** [comment]
Released a fix in [v2.2.1](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.2.1)

Please use the Bug Report issue template next time.
