### ISSUE TITLE
Support for test retries

### ISSUE THREAD

**Issue by JesseZomer** [LironEr/cypress-mochawesome-reporter#47]
**Is your feature request related to a problem? Please describe.**
Hello, excellent library 👍 

In cypress there is this thing called [Test Retries](https://docs.cypress.io/guides/guides/test-retries), where if a test failes, it will automatically try again. It will take a screenshot for every failed attempt. At the moment I'm only seeing the last attempt screenshot, however in some tests the state has changed so the retry will fail because of a different reason. Would it be possible to include the screenshots from every try?

**Describe the solution you'd like**
Lets say I have ` "retries": 2,` in my config, I would like the see included in the html file the original, attempt 1 and attempt 2 screenshots.

**Comment by LironEr** [comment]
Hey,
I'm trying to find a solution to this, currently at the end of the test mochawesome saves only the last retry attempt

I will update if I manage to find something (:

**Comment by LironEr** [comment]
Released in [v2.3.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v2.3.0)

Thanks @JesseZomer
