### ISSUE TITLE
Generated report contains json structure instead of image since version 2.3.0

### ISSUE THREAD

**Issue by pavpavel** [LironEr/cypress-mochawesome-reporter#49]
I'm not sure if this is an issue or intended behaviour, if so, then i was not able to find how to change configuration to get it working again. See below screenshots and then related content from files: **plugins\index.js:** and **support\index.ts:**

Actual report:
![image](https://user-images.githubusercontent.com/3030470/134959133-5ecd8f1f-3be8-4bf5-b4aa-2e4fd62c588f.png)
Report generated with version 2.2.1:
![image](https://user-images.githubusercontent.com/3030470/134967102-906f14b9-b449-4aad-8db9-3f86acc5ffdf.png)

**plugins\index.js:**
module.exports = (on, config) => { require('cypress-mochawesome-reporter/plugin')(on);};

**support\index.ts:**
import 'cypress-mochawesome-reporter/register';
import addContext from "mochawesome/addContext";

Cypress.Screenshot.defaults({screenshotOnRunFailure: false,});
function generateScreenshotName(test) {
    const MAX_SPEC_NAME_LENGTH = 220;
    return [test.fullTitle().slice(0, MAX_SPEC_NAME_LENGTH)," (failed) ",test.hookName,]
        .filter(Boolean)
        .join("")
        .trim();
}
afterEach(function() {
    if (this.currentTest.state === "failed") {
        cy.screenshot(generateScreenshotName(this.currentTest), {
            capture: "runner",
        });
    }
});
Cypress.on("test:after:run", (test, runnable) => {
  if (test.fail == true) {
    addContext({ test }, `${generateScreenshotName(runnable)}.png`);
  }
  return;
});

**Comment by LironEr** [comment]
There were some changes in 2.3.0 that might cause this bug, I tried to reproduce this issue but I can see the screenshots.
Can you please add your OS. node and cypress versions?

Also from what I understand from the code that you have in `support\index.ts`, you take a screenshot when a test fails, Cypress already does that [by default](https://docs.cypress.io/guides/references/configuration#Screenshots), and when using this reporter you will see the screenshot in the report without additional configuration.

**Comment by pavpavel** [comment]
> 
> 
> There were some changes in 2.3.0 that might cause this bug, I tried to reproduce this issue but I can see the screenshots. Can you please add your OS, Node.js and Cypress versions?
> 
> Also from what I understand from the code that you have in `support\index.ts`, you take a screenshot when a test fails, Cypress already does that [by default](https://docs.cypress.io/guides/references/configuration#Screenshots), and when using this reporter you will see the screenshot in the report without additional configuration. So you can probably remove all the code in this file except for:
> 
> ```
> import 'cypress-mochawesome-reporter/register';
> ```
Code was prepared there for usage of different naming logic generation(but not touched yet), anyway I reduced file `support\index.ts` as you suggested, but behavior is still the same.
I tested on 2 machines:

1. Machine: **CENTOS 8** run in docker container
- node.js: 13.14.0
- docker: 19.03.12
- cypress: 7.3.0

2. Machine: **Windows 10 (Build 19043)** 
- node.js: 16.9.1 ||  14.18.0
- cypress: 7.3.0 || 8.3.0 || 8.4.0 || 8.4.1 || 8.5.0

I tested all combination of versions on the Windows machine, but the only thing which does matter was - cypress-mochawesome-reporter: 2.3.0 || - cypress-mochawesome-reporter: 2.2.1

**Comment by LironEr** [comment]
For some reason, I can't reproduce the bug on my computer.
It will really help if you can add more info, please add to `cypress.json` this setting:
```json
"reporterOptions": {
    "saveJson": true
}
```

Full `cypress.json` example:
```json
{
  "reporter": "cypress-mochawesome-reporter",
  "video": false,
  "reporterOptions": {
    "saveJson": true
  }
}
```

After running the `cypress run` command it should create a file `cypress/reports/html/index.json`
Please post the file output here or send it to my mail lironerm@gmail.com

Thanks.

**Comment by pavpavel** [comment]
> I didnt get the log file to my mail, just the reply.

Hello, i see what i did wrong, now hopefully i send it to correct email address. 

Best regards,
Pavel

**Comment by LironEr** [comment]
Hey,

Thank you for sending the files.

From the log file I can see that the reporter only ran before running the tests, but not after.

I suspect that something is overriding the `after:run` hook, and because this reporter depends on running before and after a test run, it can cause the bug.

Please run cypress (`cypress run`) and check the logs in the console.
Do you see similar logs in the console?

![image](https://user-images.githubusercontent.com/6559921/138178645-3ec198b8-b37a-4262-a629-42bfa4d9af4c.png)

If you **see** these logs, then I'm not sure what is the problem and we will need to continue to investigate.
But you if **don't see** these logs then I think we found the problem:

Please see step 4 in the [setup](https://github.com/LironEr/cypress-mochawesome-reporter#setup), if you have something that overrides `before:run` or `after:run` you will need to manually call `beforeRunHook` & `afterRunHook` functions.

```js
const mochawesomeReporter = require('cypress-mochawesome-reporter/lib');

module.exports = (on) => {
  on('before:run', async (details) => {
    // some code...
    // ....

    await mochawesomeReporter.beforeRunHook(details);
  });

  on('after:run', async () => {
    // some code...
    // ....

    await mochawesomeReporter.afterRunHook();
  });
};
```

If this doesn't work, please send me your "cypress/plugins/index.js" file and we will continue to investigate.

Thanks.

**Comment by pavpavel** [comment]
Hello, i find out, that even code was in there, it wasn't executed due to i had 2 times `module.exports = (...`  in the 'cypress/plugins/index.js'. So it was due to mine code. Now it's working.
I'm very sorry for waisting your time.

**Comment by LironEr** [comment]
np, happy it's working 😊

**Comment by AhmedMohaidat** [comment]
@LironEr can you help me out here 
![image](https://github.com/LironEr/cypress-mochawesome-reporter/assets/95410859/f813e484-b7c0-406e-a165-22834ee8827d)
