### ISSUE TITLE
Incorrect screenshot link when error thrown on hook functions

### ISSUE THREAD

**Issue by superwesker1988** [LironEr/cypress-mochawesome-reporter#5]
Hi,

Thanks so much for the plugin! We just start using the plugin recently and it works pretty well! The only one bug that I found is that when the error is thrown on test hook (`before`, `after` etc), the link to the screenshot is incorrect because cypress decided to append name like ` -- after all hook (failed).png` to the file name. Would you accept a PR to fix the issue? Thank you!

**Comment by LironEr** [comment]
Yeah of course I will accept a fix

Thanks!

**Comment by superwesker1988** [comment]
@LironEr Thanks for the reply! Not sure why, but it seems I cannot push branch to the repo. Is there any restriction around it?

**Comment by LironEr** [comment]
Released in [v1.0.3](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v1.0.3)

Thanks!
