### ISSUE TITLE
Typescript: Report shows transpiled javascript 

### ISSUE THREAD

**Issue by SebastianDaehnrich** [LironEr/cypress-mochawesome-reporter#51]
**Is your feature request related to a problem? Please describe.**

I use the plugin @cypress/webpack-preprocessor to convert typescript to javascript.  
After I run my tests, a report is created for me that contains the transpiled Javascript.

```js
cy.login(_support_testmodel__WEBPACK_IMPORTED_MODULE_0__["default"].visitUrl);
cy.wait('@legalDataRequest').then(function () {
    _support_testmodel__WEBPACK_IMPORTED_MODULE_0__["default"].editChairman();
    _support_testmodel__WEBPACK_IMPORTED_MODULE_0__["default"].submitForm();
    _support_testmodel__WEBPACK_IMPORTED_MODULE_0__["default"].validateEditedChairmanValue();
});
```
Dependencies:
```js
{
    "cypress": "8.3.1",
    "cypress-mochawesome-reporter": "^2.3.0",
    "@cypress/webpack-preprocessor": "5.9.1"
}
```

**Is there a way to display the actual typescript code?** 

```js
cy.login(testmodel.visitUrl);
cy.wait('@legalDataRequest').then(function () {
    testmodel.editChairman();
    testmodel.submitForm();
    testmodel.validateEditedChairmanValue();
});`

**Comment by joakim-sch** [comment]
Hi @SebastianDaehnrich .
Probably not an issue anymore since its over a year since you made the request. But have you tried without the Cypress preprocessor?
I am using Typescript myself without the preprosessor. The typescript dependency handles the ts-code without problems and prints the spec code as written to the mochawesome report...

**Comment by stealthrabbi** [comment]
I'm using webpack, and not webpack preprocessor. I also have the issue where the code snippet is in javascript, and not typescript
