### ISSUE TITLE
onAfterScreenshot only work after a (non-failure) screenshot is taken

### ISSUE THREAD

**Issue by jk4235** [LironEr/cypress-mochawesome-reporter#53]
### Environment

```markdown
- OS: Win 10
- Node: 12.17.0
- cypress-mochawesome-reporter: 2.3.0
- cypress: 7.5
```

### What happened?

I found `onAfterScreenshot` only work after a **non-failure** screenshot is taken

so on v2.3.0, the reporter will not handle the screenshot which is taken by Cypress automatically when there is a failure

the function `saveScreenshotReference` will not run

``` ts
// lib/enhanceReport.js attachScreenshotsToTestContext

const screenshotsContextIndex = parsedContext.findIndex(
    (c) => typeof c === 'object' && c.value && c.title === 'cypress-mochawesome-reporter-screenshots' // ← this will not work
);
```

### Config file

```json
"reporter": "cypress-mochawesome-reporter",
"reporterOptions": {
  "saveJson": true,
  "embeddedScreenshots": true
},
```

**Comment by jk4235** [comment]
I lock version to 2.2.1 for now

**Comment by LironEr** [comment]
I just ran [one the of examples](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/examples/simple/cypress/integration/sub-dir/test1.spec.js) and I removed all `cy.screenshot()`, meaning only failed screenshots were taken.
All worked as expected

If you still have that issue please provide a repo with a way to reproduce this issue

**Comment by jk4235** [comment]
Thanks, I found the reason. My team member write a plugin that overwrite the `onAfterScreenshot` function, so the reporter doesn't work

I fix that problem.

Thanks!
