### ISSUE TITLE
Only a json file generated by the reporter

### ISSUE THREAD

**Issue by kovacsdongo** [LironEr/cypress-mochawesome-reporter#55]
### Environment

```markdown
"devDependencies": {
        "cypress-mochawesome-reporter": "^2.3.0",
        "mocha": "^9.2.0"
    },
    "dependencies": {
        "cypress": "^3.3.2",
        "cypress-cucumber-preprocessor": "^4.3.1",
        "cypress-multi-reporters": "^1.5.0",
        "junit-report-merger": "^3.0.2",
        "mocha-junit-reporter": "^2.0.2",
        "node": "^17.0.1"
    },
```

### What happened?

When i run a test only a json file put into the report folder

### Config file

```json
{
  "projectId": "9zqwhi",
  "defaultCommandTimeout": 12000,
  "pageLoadTimeout": 16000,
  "testFiles": "**/*.{feature,features,js}",
  "env": {
    "url": "https://www.kapu.hu/"
  },
  "screenshotOnRunFailure": true,
  "video": false,
  "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "reportDir": "cypress/report",
    "charts": true,
    "reportPageTitle": "citle",
    "embeddedScreenshots": true
  }
}
```

**Comment by MargaritaVacheva** [comment]
Did you add 
`  on("before:run", async (details) => {
    console.log("override before:run");
    await beforeRunHook(details);
  });

  on("after:run", async (results) => {
    console.log("override after:run");
    await afterRunHook();`
   at plugins/index.js ?

**Comment by megant** [comment]
Same here. Cypress is 9.1.0.

**Comment by mudit94** [comment]
json ile is not getting generated for me

**Comment by LironEr** [comment]
Please set [debug](https://github.com/LironEr/cypress-mochawesome-reporter#custom-options) option to `true` and paste here the log file

**Comment by WeiBinChiu** [comment]
Could you provide `index.ts` or `index.js` under `plugins` ?

**Comment by ChiuWeiBin** [comment]
Mind to share your `index.ts` or `index.js` under `plugins` folder ?

**Comment by adassoul** [comment]
Hello,
I was looking in the issues to find an issue like mine. I think this one is related :
I don't get .html files but .json files. Is this normal ?

**Comment by adassoul** [comment]
I was reading the code and discovered this bit : 
// cypress-mochawesome-reporter\lib\reporter.js

`const defaultReporterOptions = {
  overwrite: false,
  html: false,
  json: true,
};
`
maybe it's because html is false and json is true ? 
I changed it to html : true and json : false, i no longer get json files and get html files generated now but these html files aren't really html.

**Comment by adassoul** [comment]
I also am not getting the screenshots, but i'm getting a json file in the HTML when the tests fail 
![image](https://user-images.githubusercontent.com/47633088/165320632-fee6ceb9-d6a2-4e5f-a8bc-33ac73a330f6.png)

**Comment by LironEr** [comment]
@adassoul Please use `3.0.1` and set [debug](https://github.com/LironEr/cypress-mochawesome-reporter#custom-options) option to `true` and paste here the log file

**Comment by adassoul** [comment]
@LironEr It's the version I'm using. Can you tell me where I should expect the debug file to be generated? Because I added "debug": true in cypress.json, ran cypress but still didn't get any generated debug file.

**Comment by erdoganabaci** [comment]
@LironEr I have a similar problem with @adassoul. my node version is greater than 14 also when I change reporter js in node_modules it works but this method isn't good. I don't wanna change the reporter every time after ```npm install``` 
```js
const defaultReporterOptions = {
  overwrite: false,
  html: true,
  json: false,
};
``` 
In addition screenshoot doesn't work I can only see codes so how can I fix these problems.

**Comment by LironEr** [comment]
@erdoganabaci add debug flag and add here the content of the file.

If you don't find the debug file please create a repo with the problem so I can have a look.

Thanks

**Comment by erdoganabaci** [comment]
@LironEr here repo [https://github.com/erdoganabaci/cypress-reporter-bug](https://github.com/erdoganabaci/cypress-reporter-bug) I explain all bugs and how you can set up in the readme file

**Comment by LironEr** [comment]
The issue was that your plugins file wasn't really used by cypress

https://github.com/erdoganabaci/cypress-reporter-bug/pull/1

**Comment by erdoganabaci** [comment]
thanks for quick reply it works on javascript cypress file but if I want to change pluginFile location it returns again same problem generating JSON file :(  
My main project built in typescript cypress files. That's why I need it dist folder but ```cypress-mochawesome-reporter``` doesn't work when I change diffrent locations.
change locate instead of default **doesn't work**=>    
```json 
"pluginsFile": "cypress/dist/plugins/index.js"
```

default location works fine =>
```json 
"pluginsFile": "cypress/plugins/index.js"
```

**Comment by erdoganabaci** [comment]
@LironEr  Another question about screenshots doesn't work how can I see screenshots in an HTML output file?

**Comment by LironEr** [comment]
Sorry for the late response, missed those comments.

If the issue still relevant please create a repo with the problem so I can have a look.

**Comment by erdoganabaci** [comment]
@LironEr I fixed thanks!

**Comment by majco333** [comment]
Hello, I have the same problem. I am attaching the log:
![image](https://user-images.githubusercontent.com/4101721/198735936-5d10be7a-f6ed-46f9-b436-5e64c8766b4b.png)

@LironEr How can you fix it? Reverse row 15 and 16...
