### ISSUE TITLE
unable to access index.json created by mochawesome for parsing

### ISSUE THREAD

**Issue by mudit94** [LironEr/cypress-mochawesome-reporter#57]
Hi Team, I want to include the total test count, passed count and failed count in a email . i am triggering the cypress test from a jenkins/gitlab pipeline
I am unable to access index.json created by mochawesome reporter which i want to parse to draft the email

**Comment by adassoul** [comment]
Hello,
I was looking in the issues to find an issue like mine. I think this one is related : 
I don't get .html files but .json files. Is this normal ?

**Comment by adassoul** [comment]
//cypress.json
`{
  "reporter":"cypress-mochawesome-reporter",
  "reporterOptions": {
    "reportDir": "cypress/reports",
    "charts": true,
    "reportPageTitle": "My Test Suite",
    "embeddedScreenshots": true,
    "inlineAssets": true
  },
  "retries": {
    "runMode": 2,
    "openMode" : 2
  },
  "ignoreTestFiles": [
    "variables*",
    "test*",
    "url_apiCalls.json"
  ],
  "videoCompression": 1,
  "failOnStatusCode": false
}
`

**Comment by LironEr** [comment]
@adassoul no, you should get an HTML file.
Please add `debug: true` to `reporterOptions` and add here the log file

**Comment by LironEr** [comment]
In the same folder as your package.json.
If you don't find the debug file please create a repo with the problem so I can have a look.

Thanks
