### ISSUE TITLE
marge dependency is vulnerable 

### ISSUE THREAD

**Issue by rromanv** [LironEr/cypress-mochawesome-reporter#58]
### Environment

```markdown
- OS: Ubuntu 22.04
- Node: 17.6.0
- cypress-mochawesome-reporter: 2.3.0
- cypress: 9.3.1
```

### What happened?

I noticed on the npm audit the next output

Inefficient Regular Expression Complexity in validator.js - https://github.com/advisories/GHSA-qgmg-gppg-76g5
No fix available
node_modules/validator
  mochawesome-report-generator  1.1.1 - 5.2.0
  Depends on vulnerable versions of validator
  Depends on vulnerable versions of yargs
  node_modules/mochawesome-report-generator
    cypress-mochawesome-reporter  *
    Depends on vulnerable versions of mochawesome-report-generator
    node_modules/cypress-mochawesome-reporter
    mochawesome  2.1.0 - 6.3.1
    Depends on vulnerable versions of mochawesome-report-generator
    node_modules/mochawesome

### Config file

```json
{
  "viewportHeight": 1080,
  "viewportWidth": 1920,
  "component": {
    "viewportHeight": 1024,
    "viewportWidth": 1280
  },
  "ignoreTestFiles": "**/*.md",
  "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "reportDir": "cypress/reports",
    "charts": true,
    "reportPageTitle": "STC App Team Checklist",
    "embeddedScreenshots": true,
    "inlineAssets": true
  },
  "video": false
}
```

**Comment by LironEr** [comment]
Fixed in [v3.0.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v3.0.0)
