### ISSUE TITLE
Screenshots doesnt get added into report, just shows the path in additional info

### ISSUE THREAD

**Issue by PadalaSandeep** [LironEr/cypress-mochawesome-reporter#69]
![Screenshot 2022-04-09 at 2 21 46 PM](https://user-images.githubusercontent.com/34596007/162564336-21f05716-c536-4907-b1dd-0d967a9f85cb.png)

Using  "cypress": "7.7.0", and "cypress-mochawesome-reporter": "3.0.0"
Codebase Github link: [CypressUIAutomation](https://github.com/PadalaSandeep/CypressUIAutomation)

**Comment by LironEr** [comment]
[v3.0.1](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v3.0.1) should fix this issue, if not please comment here

Thank you for reporting this issue 👍

**Comment by PadalaSandeep** [comment]
Issue is Fixed now, Thanks @LironEr
