### ISSUE TITLE
How to export execution result to slack?

### ISSUE THREAD

**Issue by rajann44** [LironEr/cypress-mochawesome-reporter#70]
We donot see json files of results, is it possible to post execution results to slack?

**Comment by LironEr** [comment]
You can export json results with `saveJson: true`:

```json
{
  "reporter": "cypress-mochawesome-reporter",
  "video": false,
  "reporterOptions": {
    "saveJson": true
  }
}
```

As for the Slack integration, you can try use [cypress-slack-reporter](https://github.com/you54f/cypress-slack-reporter), but I never tried it, so Im not sure how to use it (:

**Comment by rajann44** [comment]
THanks @LironEr

**Comment by rajann44** [comment]
The [cypress-slack-reporter](https://github.com/you54f/cypress-slack-reporter), have Pre-Requisites for:
    yarn add mochawesome --dev
    yarn add mochawesome-merge --dev
    yarn add mochawesome-report-generator --dev
    yarn add cypress-multi-reporters --dev

So I guess it wont work with this.

maybe I can send a post request by extracting data from json

**Comment by LironEr** [comment]
This reporter already does all these steps behind the scenes.
So I understand correctly, you can run this reporter, and then the slack reporter.

```sh
./node_modules/.bin/cypress-slack-reporter-full --reportDir cypress/reports/html
```

it will find `index.json` file, parse it and send slack message
