### ISSUE TITLE
Be able to add test context

### ISSUE THREAD

**Issue by mlegait** [LironEr/cypress-mochawesome-reporter#75]
According to the documentation, it's possible to add test context to Mochawesome reports: https://github.com/adamgruber/mochawesome#adding-test-context

So I tried to do it on top of `cypress-mochawesome-reporter` as described in Mochawesome README. But it does nothing.

Could it be possible to have a way to add test context?

Thank you very much for your help 😄

**Comment by LironEr** [comment]
See [v3.1.0](https://github.com/LironEr/cypress-mochawesome-reporter/releases/tag/v3.1.0) release notes

Thanks.

**Comment by mlegait** [comment]
Thank you so much @LironEr !
