### ISSUE TITLE
"saveJson": false still creates json file

### ISSUE THREAD

**Issue by quad5** [LironEr/cypress-mochawesome-reporter#77]
I have the following setting in `cypress.json` file:

> "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "saveJson": false
  },

I see this message in Jenkins' console log: `[mochawesome] Report JSON saved to /tmp/jenkins/workspace/ession-Cypress_parallelExecution/cypress/cypress/reports/desktopView/.jsons/mochawesome.json`

**Comment by LironEr** [comment]
[Under the hood](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/lib/reporter.js#L8) for this reporter to work properly, Mochawesome must save JSON files to the `.jsons` folder, but after a run, this reporter deletes the folder.

`saveJson` is an option we pass to `mochawesome-report-generator` when [creating](https://github.com/LironEr/cypress-mochawesome-reporter/blob/master/lib/generateReport.js#L25) the final HTML file.

By default, `saveJson` is false.
If you set it to true it will create one big JSON file, combining all the files in the `.jsons` folder.
