### ISSUE TITLE
Option to display percentage of the passed/failed tests on the report.

### ISSUE THREAD

**Issue by hienpham15** [LironEr/cypress-mochawesome-reporter#83]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I would like an option to display percentage along side the pie chart, on top right of the report.

**Describe alternatives you've considered**
Display a bar of percentage of passed/failed tests.

**Additional context**

**Comment by LironEr** [comment]
Hey,
This reporter uses [mochawesome-report-generator](https://github.com/adamgruber/mochawesome-report-generator) under the hood, the generator generates the HTML so you should suggest that feature there (:
