### ISSUE TITLE
Error when generate report in parallel execution on github workflow

### ISSUE THREAD

**Issue by spatel2605** [LironEr/cypress-mochawesome-reporter#98]
### Environment

```markdown
- OS: ubuntu-latest
- Node: 14.19.0
- cypress-mochawesome-reporter: 6.2.0
- cypress: 9.6.1
```

### What happened?

Following error thrown when run tests in parallel mode in github workflow:

Error: Pattern /cypress/reports/html/.jsons/*.json matched no report files

### Config file

```json
"reporter": "cypress-mochawesome-reporter",
```

**Comment by LironEr** [comment]
Please provide more information, add log file, add your full config and state the correct `cypress-mochawesome-reporter`
Even better, create a repo and describe the steps to reproduce the bug.
